name: to_do_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none' # Remove this line if you plan to publish

# Versioning information
version: 1.0.0+1

# Specify Dart SDK version
environment:
  sdk: ^3.7.2 # Ensure your Flutter version supports this Dart version

# Dependencies required for your app
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8 # Consider updating to the latest version

# Dev dependencies for testing and linting
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Consider checking for a newer version

# Flutter-specific configurations
flutter:
  uses-material-design: true
  assets:
    - assets/images/ # Ensure proper indentation

